#!/usr/bin/env bash
#
# Workstation Installer
# Initializes a new SSOT workspace for agent-human collaboration
#

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check dependencies
check_dependencies() {
    log_info "Checking dependencies..."
    
    if ! command -v git &> /dev/null; then
        log_error "git is required but not installed"
        exit 1
    fi
    
    if ! command -v gh &> /dev/null; then
        log_warn "GitHub CLI (gh) not found. Remote repository creation will be skipped."
        GH_AVAILABLE=false
    else
        GH_AVAILABLE=true
    fi
    
    log_success "Dependencies OK"
}

# Load or create environment
setup_environment() {
    log_info "Setting up environment..."
    
    if [[ -f ".env" ]]; then
        log_info "Loading existing .env file"
        # shellcheck source=/dev/null
        source .env
    fi
    
    # Get organization name
    if [[ -z "${ORG_NAME:-}" ]]; then
        read -rp "Organization name (e.g., MyOrg): " ORG_NAME
    else
        log_info "Using ORG_NAME from .env: $ORG_NAME"
    fi
    
    # Get GitHub owner
    if [[ -z "${GITHUB_OWNER:-}" ]]; then
        read -rp "GitHub owner/username: " GITHUB_OWNER
    else
        log_info "Using GITHUB_OWNER from .env: $GITHUB_OWNER"
    fi
    
    # Save environment
    cat > .env <<EOF
# ===============================
# Workstation Configuration
# ===============================

ORG_NAME=$ORG_NAME
GITHUB_OWNER=$GITHUB_OWNER
WORKSTATION_VERSION=1.0.0

# Generated on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
EOF
    
    log_success "Environment configured"
}

# Create SSOT structure
create_ssot_structure() {
    log_info "Creating SSOT structure..."
    
    local ssot_dir="SSOT"
    
    # Create directories
    mkdir -p "$ssot_dir"/{KBs,Seats,Projects,Sprints}
    
    # Create SSOT root documentation
    cat > "$ssot_dir/SSOT.md" <<EOF
# $ORG_NAME SSOT

**Single Source of Truth for $ORG_NAME**

This is the organizational root where humans and AI agents collaborate.

## Structure

\`\`\`
SSOT/
├── KBs/           # Knowledge Bases (submodules)
│   └── KB-Core/   # Core semantics and definitions
├── Seats/         # Agent contexts
├── Projects/      # Active work
└── Sprints/       # Time-boxed iterations
\`\`\`

## Quick Start

1. **Initialize a Seat**: Creates an isolated agent workspace
   \`\`\`bash
   bash scripts/create-seat.sh <seat-name>
   \`\`\`

2. **Add Knowledge**: Link additional KBs
   \`\`\`bash
   git submodule add <kb-repo-url> KBs/<kb-name>
   \`\`\`

3. **Create Project**: Start organized work
   \`\`\`bash
   bash scripts/create-project.sh <project-name>
   \`\`\`

## Principles

- **Canonical**: One source of truth for each entity
- **Modular**: KBs can be shared across organizations
- **Versioned**: Everything is git-tracked
- **Agent-Ready**: Structured for AI consumption

---
*Generated by Workstation v1.0.0*
EOF

    # Create KB-Core directory and initial content
    mkdir -p "$ssot_dir/KBs/KB-Core"
    cat > "$ssot_dir/KBs/KB-Core/KB-Core.md" <<EOF
# KB-Core v1.0.0

**Core Semantic Foundation for $ORG_NAME**

## Purpose

Defines the formal semantics, entities, and structural rules used across the organization.

## Entity Definitions

### Organization
- **Name**: $ORG_NAME
- **Root**: This SSOT
- **Owner**: $GITHUB_OWNER

### Seat
An isolated context for an AI agent with:
- Dedicated memory space
- Specific tools/configuration
- Clear boundaries and permissions

### Project
A scoped body of work with:
- Defined objectives
- Associated Seats
- Linked KBs

### Sprint
Time-boxed iteration with:
- Start/end dates
- Associated Projects
- Deliverables

## Naming Conventions

- **Seats**: PascalCase (e.g., Developer, Researcher)
- **Projects**: kebab-case (e.g., api-redesign)
- **Sprints**: YYYY-MM-description (e.g., 2026-03-foundation)

## Extension

Extend this KB by:
1. Adding entity definitions
2. Creating domain-specific KBs as submodules
3. Referencing (never redefining) Core entities

---
*Canonical semantics for $ORG_NAME*
EOF

    # Create initial directories for Seats, Projects, Sprints
    cat > "$ssot_dir/Seats/README.md" <<EOF
# Seats

Agent workspaces live here.

Each Seat is a git submodule with its own:
- AGENT.md (identity)
- MEMORY.md (long-term memory)
- TOOLS.md (available tools)

## Active Seats

<!-- List active seats here -->

## Creating a Seat

\`\`\`bash
bash ../scripts/create-seat.sh <seat-name>
\`\`\`
EOF

    cat > "$ssot_dir/Projects/README.md" <<EOF
# Projects

Organized work streams.

Each project directory contains:
- Project definition
- Links to relevant Seats
- Associated KBs
- Sprint references

## Active Projects

<!-- List active projects here -->
EOF

    cat > "$ssot_dir/Sprints/README.md" <<EOF
# Sprints

Time-boxed iterations.

## Current Sprint

<!-- Link to current sprint -->

## Past Sprints

<!-- Archive completed sprints -->
EOF

    log_success "SSOT structure created in $ssot_dir/"
}

# Initialize git repository
init_git_repo() {
    log_info "Initializing git repository..."
    
    if [[ ! -d ".git" ]]; then
        git init
        log_success "Git repository initialized"
    else
        log_info "Git repository already exists"
    fi
    
    # Create .gitignore
    cat > .gitignore <<'EOF'
# Environment
.env
.env.local
!.env.example

# OS
.DS_Store
Thumbs.db

# Editors
.vscode/
.idea/
*.swp
*.swo

# Logs
*.log
logs/

# Temp
.tmp/
temp/
.cache/

# Runtime artifacts
*.pid
*.lock

# Keep submodules
!SSOT/KBs/*/
!SSOT/Seats/*/
EOF

    log_success ".gitignore created"
}

# Create utility scripts
create_scripts() {
    log_info "Creating utility scripts..."
    
    mkdir -p scripts
    
    # Create seat script
    cat > scripts/create-seat.sh <<'EOFSCRIPT'
#!/usr/bin/env bash
# Create a new Seat (agent workspace)

set -euo pipefail

SEAT_NAME="${1:-}"
if [[ -z "$SEAT_NAME" ]]; then
    echo "Usage: $0 <seat-name>"
    exit 1
fi

SEAT_DIR="SSOT/Seats/$SEAT_NAME"

if [[ -d "$SEAT_DIR" ]]; then
    echo "Error: Seat '$SEAT_NAME' already exists"
    exit 1
fi

mkdir -p "$SEAT_DIR"

cat > "$SEAT_DIR/AGENT.md" <<EOF
# $SEAT_NAME

**Role**: <!-- Define agent role -->
**Created**: $(date -u +"%Y-%m-%d")

## Purpose

<!-- What this agent does -->

## Boundaries

<!-- Clear permissions and limits -->

## Tools

<!-- Available capabilities -->

## Memory

<!-- Key information to retain -->
EOF

cat > "$SEAT_DIR/MEMORY.md" <<EOF
# Memory: $SEAT_NAME

<!-- Persistent context for this agent -->
EOF

cat > "$SEAT_DIR/TOOLS.md" <<EOF
# Tools: $SEAT_NAME

<!-- Tool configurations and credentials -->
EOF

echo "Seat created: $SEAT_DIR"
echo "Next steps:"
echo "  1. Edit $SEAT_DIR/AGENT.md to define the agent"
echo "  2. Commit: git add $SEAT_DIR && git commit -m 'Add seat: $SEAT_NAME'"
EOFSCRIPT
    chmod +x scripts/create-seat.sh

    # Create project script
    cat > scripts/create-project.sh <<'EOFSCRIPT'
#!/usr/bin/env bash
# Create a new Project

set -euo pipefail

PROJECT_NAME="${1:-}"
if [[ -z "$PROJECT_NAME" ]]; then
    echo "Usage: $0 <project-name>"
    exit 1
fi

PROJECT_DIR="SSOT/Projects/$PROJECT_NAME"

if [[ -d "$PROJECT_DIR" ]]; then
    echo "Error: Project '$PROJECT_NAME' already exists"
    exit 1
fi

mkdir -p "$PROJECT_DIR"

cat > "$PROJECT_DIR/README.md" <<EOF
# Project: $PROJECT_NAME

**Status**: Planning
**Created**: $(date -u +"%Y-%m-%d")

## Objective

<!-- What this project achieves -->

## Scope

<!-- Inclusions and exclusions -->

## Related

- **Seats**: <!-- Link relevant seats -->
- **KBs**: <!-- Link knowledge bases -->
- **Sprints**: <!-- Link sprints -->

## Deliverables

- [ ] <!-- Deliverable 1 -->
- [ ] <!-- Deliverable 2 -->

## Decisions

<!-- Key decisions log -->
EOF

echo "Project created: $PROJECT_DIR"
echo "Next steps:"
echo "  1. Edit $PROJECT_DIR/README.md"
echo "  2. Commit: git add $PROJECT_DIR && git commit -m 'Add project: $PROJECT_NAME'"
EOFSCRIPT
    chmod +x scripts/create-project.sh

    # Create sprint script
    cat > scripts/create-sprint.sh <<'EOFSCRIPT'
#!/usr/bin/env bash
# Create a new Sprint

set -euo pipefail

SPRINT_NAME="${1:-}"
if [[ -z "$SPRINT_NAME" ]]; then
    echo "Usage: $0 <sprint-name>"
    echo "Example: $0 2026-03-foundation"
    exit 1
fi

SPRINT_DIR="SSOT/Sprints/$SPRINT_NAME"

if [[ -d "$SPRINT_DIR" ]]; then
    echo "Error: Sprint '$SPRINT_NAME' already exists"
    exit 1
fi

mkdir -p "$SPRINT_DIR"

cat > "$SPRINT_DIR/README.md" <<EOF
# Sprint: $SPRINT_NAME

**Status**: Planning
**Start**: <!-- YYYY-MM-DD -->
**End**: <!-- YYYY-MM-DD -->

## Goals

<!-- Sprint objectives -->

## Projects

<!-- Linked projects -->

## Deliverables

- [ ] <!-- Item 1 -->
- [ ] <!-- Item 2 -->

## Retrospective

<!-- Post-sprint review -->
EOF

echo "Sprint created: $SPRINT_DIR"
echo "Next steps:"
echo "  1. Edit $SPRINT_DIR/README.md"
echo "  2. Commit: git add $SPRINT_DIR && git commit -m 'Add sprint: $SPRINT_NAME'"
EOFSCRIPT
    chmod +x scripts/create-sprint.sh

    log_success "Utility scripts created in scripts/"
}

# Create initial commit
create_initial_commit() {
    log_info "Creating initial commit..."
    
    git add -A
    git commit -m "Initial Workstation setup for $ORG_NAME

- SSOT structure with KBs, Seats, Projects, Sprints
- KB-Core semantic foundation
- Utility scripts for creating Seats, Projects, Sprints
- Environment configuration

Generated by Workstation v1.0.0"

    log_success "Initial commit created"
}

# Main execution
main() {
    echo "=========================================="
    echo "  Workstation Installer"
    echo "  Agent-Ready Organizational Workspace"
    echo "=========================================="
    echo ""
    
    check_dependencies
    setup_environment
    create_ssot_structure
    init_git_repo
    create_scripts
    create_initial_commit
    
    echo ""
    echo "=========================================="
    log_success "Workstation initialized successfully!"
    echo "=========================================="
    echo ""
    echo "Next steps:"
    echo ""
    echo "  1. Create your first Seat (agent workspace):"
    echo "     bash scripts/create-seat.sh MyAgent"
    echo ""
    echo "  2. Create a Project:"
    echo "     bash scripts/create-project.sh my-project"
    echo ""
    echo "  3. Push to GitHub (optional):"
    echo "     git remote add origin https://github.com/$GITHUB_OWNER/$ORG_NAME-SSOT.git"
    echo "     git push -u origin main"
    echo ""
    echo "Documentation: README.md"
    echo ""
}

# Run main function
main "$@"
