#!/usr/bin/env bash
#
# Workstation Installer
# Creates SSOT-$ORG_NAME, kb-core, and initializes structure
#

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

check_dependencies() {
    log_info "Checking dependencies..."
    if ! command -v git &> /dev/null; then
        log_error "git is required but not installed"
        exit 1
    fi
    log_success "Dependencies OK"
}

setup_environment() {
    log_info "Setting up environment..."
    
    if [[ -f ".env" ]]; then
        source .env
    fi
    
    if [[ -z "${ORG_NAME:-}" ]]; then
        read -rp "Organization name (e.g., MyOrg): " ORG_NAME
    fi
    
    if [[ -z "${GITHUB_OWNER:-}" ]]; then
        read -rp "GitHub owner/username: " GITHUB_OWNER
    fi
    
    cat > .env <<EOF
# Workstation Configuration
ORG_NAME=$ORG_NAME
GITHUB_OWNER=$GITHUB_OWNER
WORKSTATION_VERSION=1.0.0
EOF
    
    log_success "Environment configured for: $ORG_NAME"
}

create_kb_core() {
    local kb_path="../kb-core"
    
    if [[ -d "$kb_path" ]]; then
        log_warn "kb-core already exists, skipping"
        return
    fi
    
    log_info "Creating kb-core repository..."
    
    mkdir -p "$kb_path"
    cd "$kb_path"
    git init 2>/dev/null || true
    
    cat > README.md <<EOF
# KB-Core v1.0.0

**Core Semantic Foundation for Workstation Organizations**

## Purpose

Defines the formal semantics, entities, and structural rules used across all SSOTs.

## Entity Definitions

### Organization
- **Name**: Organization identifier
- **SSOT**: Root repository reference
- **Owner**: GitHub owner

### Seat
An isolated context for an AI agent:
- Repository: Seat-\$SeatName-\$Org
- Contains: .openclaw/workspace/
- Defines: Identity, memory, tools

### Project
A scoped body of work:
- Repository: Project-\$ProjectName-\$Org  
- Contains: Objectives, scope, deliverables
- Links: Seats, KBs

## Naming Conventions

- **Seats**: Seat-PascalCase-Org (e.g., Seat-Developer-Acme)
- **Projects**: Project-PascalCase-Org (e.g., Project-ApiV2-Acme)
- **KBs**: KB-PascalCase (e.g., KB-Core, KB-Engineering)

## Versioning

- **MAJOR**: Semantic breaking change
- **MINOR**: Additive extension
- **PATCH**: Clarification, no semantic change
EOF

    cat > .gitignore <>'GITIGNORE'
.env
.env.*
!.env.example
.DS_Store
.vscode/
.idea/
*.swp
GITIGNORE

    git add -A
    git commit -m "Initial KB-Core v1.0.0"
    
    cd "$SCRIPT_DIR"
    log_success "kb-core created: $kb_path"
}

create_ssot() {
    local ssot_name="SSOT-${ORG_NAME}"
    local ssot_path="../${ssot_name}"
    
    if [[ -d "$ssot_path" ]]; then
        log_error "SSOT '$ssot_path' already exists"
        exit 1
    fi
    
    log_info "Creating SSOT repository: $ssot_name"
    
    mkdir -p "$ssot_path"
    cd "$ssot_path"
    git init 2>/dev/null || true
    
    mkdir -p KBs Seats Projects
    
    # SSOT root documentation
    cat > SSOT.md <<EOF
# SSOT: $ORG_NAME

**Single Source of Truth for $ORG_NAME**

## Structure

\`\`\`
SSOT-$ORG_NAME/
├── KBs/              # Knowledge Bases (submodules)
│   └── KB-Core/
├── Seats/            # Agent workspaces (submodules)
│   └── Seat-Name-$ORG_NAME/
└── Projects/         # Work streams (submodules)
    └── Project-Name-$ORG_NAME/
\`\`\`

## Quick Start

### Add KB
\`\`\`bash
cd KBs
git submodule add https://github.com/$GITHUB_OWNER/kb-engineering.git
\`\`\`

### Add Seat
\`\`\`bash
cd Seats
git submodule add ../Seat-Developer-$ORG_NAME.git
\`\`\`

### Add Project
\`\`\`bash
cd Projects
git submodule add ../Project-ApiV2-$ORG_NAME.git
\`\`\`

---
*Generated by Workstation v1.0.0*
EOF

    # KBs README
    cat > KBs/README.md <<EOF
# Knowledge Bases

Git submodules containing domain knowledge.

## Add KB
\`\`\`bash
cd KBs
git submodule add https://github.com/$GITHUB_OWNER/kb-<name>.git
\`\`\`
EOF

    # Seats README
    cat > Seats/README.md <<EOF
# Seats

Agent workspaces (submodules).

Naming: Seat-\$Name-$ORG_NAME

## Add Seat
\`\`\`bash
cd Seats
git submodule add ../Seat-<Name>-$ORG_NAME.git
\`\`\`

## Create New Seat
\`\`\`bash
bash ../workstation/scripts/create-seat.sh <name>
\`\`\`
EOF

    # Projects README
    cat > Projects/README.md <<EOF
# Projects

Work streams (submodules).

Naming: Project-\$Name-$ORG_NAME

## Add Project
\`\`\`bash
cd Projects
git submodule add ../Project-<Name>-$ORG_NAME.git
\`\`\`

## Create New Project
\`\`\`bash
bash ../workstation/scripts/create-project.sh <name>
\`\`\`
EOF

    cat > .gitignore <>'GITIGNORE'
.env
.env.*
!.env.example
.DS_Store
.vscode/
.idea/
*.swp
!KBs/*/
!Seats/*/
!Projects/*/
GITIGNORE

    git add -A
    git commit -m "Initial SSOT for $ORG_NAME"
    
    # Add KB-Core as submodule
    git submodule add "../../kb-core" KBs/KB-Core
    git commit -m "Add KB-Core submodule"
    
    cd "$SCRIPT_DIR"
    log_success "SSOT created: $ssot_path"
}

main() {
    echo "=========================================="
    echo "  Workstation Installer"
    echo "=========================================="
    echo ""
    
    check_dependencies
    setup_environment
    create_kb_core
    create_ssot
    
    echo ""
    echo "=========================================="
    log_success "Workstation initialized!"
    echo "=========================================="
    echo ""
    echo "Created:"
    echo "  📁 ../SSOT-${ORG_NAME}/       # Your SSOT"
    echo "  📁 ../kb-core/                # Core KB"
    echo ""
    echo "Next steps:"
    echo ""
    echo "  1. cd ../SSOT-${ORG_NAME}"
    echo ""
    echo "  2. Create your first Seat:"
    echo "     bash ../workstation/scripts/create-seat.sh Developer"
    echo "     cd ../SSOT-${ORG_NAME}"
    echo "     git submodule add ../Seat-Developer-${ORG_NAME} Seats/Developer"
    echo ""
    echo "  3. Create your first Project:"
    echo "     bash ../workstation/scripts/create-project.sh api-v2"
    echo "     cd ../SSOT-${ORG_NAME}"
    echo "     git submodule add ../Project-ApiV2-${ORG_NAME} Projects/ApiV2"
    echo ""
    echo "  4. Push to GitHub:"
    echo "     cd ../SSOT-${ORG_NAME}"
    echo "     git remote add origin https://github.com/$GITHUB_OWNER/SSOT-${ORG_NAME}.git"
    echo "     git push -u origin main"
    echo ""
}

main "$@"
