#!/usr/bin/env bash
#
# Workstation Installer
# Creates a new SSOT-$ORGNAME repository for agent-human collaboration
#

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Check dependencies
check_dependencies() {
    log_info "Checking dependencies..."
    if ! command -v git &> /dev/null; then
        log_error "git is required but not installed"
        exit 1
    fi
    log_success "Dependencies OK"
}

# Setup environment
setup_environment() {
    log_info "Setting up environment..."
    
    if [[ -f ".env" ]]; then
        source .env
    fi
    
    if [[ -z "${ORG_NAME:-}" ]]; then
        read -rp "Organization name (e.g., MyOrg): " ORG_NAME
    fi
    
    if [[ -z "${GITHUB_OWNER:-}" ]]; then
        read -rp "GitHub owner/username: " GITHUB_OWNER
    fi
    
    # Save environment
    cat > .env <<EOF
# ===============================
# Workstation Configuration
# ===============================

ORG_NAME=$ORG_NAME
GITHUB_OWNER=$GITHUB_OWNER
WORKSTATION_VERSION=1.0.0

# Generated on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
EOF
    
    log_success "Environment configured for: $ORG_NAME"
}

# Create SSOT repository
create_ssot_repo() {
    local ssot_name="SSOT-${ORG_NAME}"
    local ssot_path="../${ssot_name}"
    
    log_info "Creating SSOT repository: $ssot_name"
    
    if [[ -d "$ssot_path" ]]; then
        log_error "Directory $ssot_path already exists"
        exit 1
    fi
    
    mkdir -p "$ssot_path"
    cd "$ssot_path"
    git init
    
    # Create directory structure (empty, ready for submodules)
    mkdir -p KBs Seats Projects Sprints
    
    # Create root SSOT.md
    cat > SSOT.md <<EOF
# $ORG_NAME SSOT

**Single Source of Truth for $ORG_NAME**

This is the organizational root where humans and AI agents collaborate.

## Structure

\`\`\`
.
├── KBs/           # Knowledge Bases (git submodules)
├── Seats/         # Agent workspaces (git submodules)
├── Projects/      # Active work (local)
└── Sprints/       # Time-boxed iterations (local)
\`\`\`

## Quick Start

### Add a Knowledge Base
\`\`\`bash
cd KBs
git submodule add https://github.com/$GITHUB_OWNER/kb-<name>.git
\`\`\`

### Add a Seat
\`\`\`bash
cd Seats
git submodule add https://github.com/$GITHUB_OWNER/seat-<name>.git
\`\`\`

### Create a Project
Projects are local to this SSOT:
\`\`\`bash
mkdir Projects/<project-name>
cat > Projects/<project-name>/README.md <>'PROJECT'
# Project: <project-name>
# ...
PROJECT
\`\`\`

## Principles

- **Canonical**: One source of truth for each entity
- **Modular**: KBs and Seats are reusable across organizations
- **Versioned**: Everything is git-tracked
- **Agent-Ready**: Structured for AI consumption

---
*Generated by Workstation v1.0.0*
EOF

    # Create KBs README
    cat > KBs/README.md <<EOF
# Knowledge Bases

Knowledge Bases are git submodules containing domain knowledge.

## Structure

\`\`\`
KBs/
├── KB-Core/          # Core semantics (required submodule)
├── KB-Engineering/   # Engineering standards
├── KB-Brand/         # Brand guidelines
└── ...
\`\`\`

## Adding a KB

\`\`\`bash
cd KBs
git submodule add https://github.com/$GITHUB_OWNER/kb-<name>.git
cd ..
git add .gitmodules KBs/<name>
git commit -m "Add KB-<name> submodule"
\`\`\`

## Creating a New KB

To create a new KB repository:

\`\`\`bash
# Create standalone KB repo
git init kb-<name>
cd kb-<name>
echo "# KB-<name>" > README.md

# Add .gitignore
cat > .gitignore <>'GITIGNORE'
# Environment
.env
.env.*
!.env.example

# OS
.DS_Store

# Editor
.vscode/
.idea/
*.swp
GITIGNORE

git add -A
git commit -m "Initial KB commit"
git remote add origin https://github.com/$GITHUB_OWNER/kb-<name>.git
git push -u origin main
\`\`\`

Then add it as a submodule to this SSOT.
EOF

    # Create Seats README
    cat > Seats/README.md <<EOF
# Seats

Seats are git submodules containing agent workspaces.

Each Seat has the structure:
\`\`\`
Seat-Name/
├── .openclaw/
│   └── workspace/       # Agent workspace files
│       ├── AGENT.md     # Agent identity
│       ├── MEMORY.md    # Long-term memory
│       ├── TOOLS.md     # Tool configuration
│       └── ...
├── .gitignore
└── README.md
\`\`\`

## Adding a Seat

\`\`\`bash
cd Seats
git submodule add https://github.com/$GITHUB_OWNER/seat-<name>.git
cd ..
git add .gitmodules Seats/<name>
git commit -m "Add Seat-<name> submodule"
\`\`\`

## Creating a New Seat

Use the workstation script:

\`\`\`bash
# From the SSOT directory
bash ../workstation/scripts/create-seat.sh <seat-name>
\`\`\`

Or manually:

\`\`\`bash
# Create standalone Seat repo
git init seat-<name>
cd seat-<name>

# Create .openclaw structure
mkdir -p .openclaw/workspace

# Add agent files
cat > .openclaw/workspace/AGENT.md <>'AGENT'
# <name>

**Role**: <!-- Define agent role -->

## Purpose
<!-- What this agent does -->

## Boundaries
<!-- Permissions and limits -->
AGENT

cat > .openclaw/workspace/MEMORY.md <>'MEMORY'
# Memory: <name>

<!-- Persistent context -->
MEMORY

cat > .openclaw/workspace/TOOLS.md <>'TOOLS'
# Tools: <name>

<!-- Tool configurations -->
TOOLS

# Add .gitignore
cat > .gitignore <>'GITIGNORE'
# Environment
.env
.env.*
!.env.example

# OS
.DS_Store

# Editor
.vscode/
.idea/
*.swp

# OpenClaw runtime (optional - depends on preference)
# .openclaw/workspace/.tmp/
GITIGNORE

git add -A
git commit -m "Initial Seat commit"
git remote add origin https://github.com/$GITHUB_OWNER/seat-<name>.git
git push -u origin main
\`\`\`

Then add it as a submodule to this SSOT.
EOF

    # Create Projects README
    cat > Projects/README.md <<EOF
# Projects

Projects are work streams stored locally in this SSOT.

## Creating a Project

\`\`\`bash
mkdir Projects/<project-name>
cat > Projects/<project-name>/README.md <>'PROJECT'
# Project: <project-name>

**Status**: Planning
**Created**: $(date +%Y-%m-%d)

## Objective
<!-- What this project achieves -->

## Scope
<!-- Inclusions and exclusions -->

## Related
- **Seats**: <!-- Link seats -->
- **KBs**: <!-- Link KBs -->
- **Sprints**: <!-- Link sprints -->

## Deliverables
- [ ] <!-- Item 1 -->
PROJECT
git add Projects/<project-name>
git commit -m "Add project: <project-name>"
\`\`\`
EOF

    # Create Sprints README
    cat > Sprints/README.md <<EOF
# Sprints

Sprints are time-boxed iterations stored locally.

## Creating a Sprint

\`\`\`bash
mkdir Sprints/<sprint-name>
cat > Sprints/<sprint-name>/README.md <>'SPRINT'
# Sprint: <sprint-name>

**Status**: Planning
**Start**: <!-- YYYY-MM-DD -->
**End**: <!-- YYYY-MM-DD -->

## Goals
<!-- Sprint objectives -->

## Projects
<!-- Linked projects -->

## Deliverables
- [ ] <!-- Item 1 -->

## Retrospective
<!-- Post-sprint review -->
SPRINT
git add Sprints/<sprint-name>
git commit -m "Add sprint: <sprint-name>"
\`\`\`
EOF

    # Create main .gitignore
    cat > .gitignore <<'GITIGNORE'
# Environment
.env
.env.*
!.env.example

# OS
.DS_Store
Thumbs.db

# Editors
.vscode/
.idea/
*.swp
*.swo

# Logs
*.log
logs/

# Temp
.tmp/
temp/
.cache/

# Do not ignore submodules
!KBs/*/
!Seats/*/
GITIGNORE

    # Initial commit
    git add -A
    git commit -m "Initial SSOT for $ORG_NAME

- SSOT structure: KBs/, Seats/, Projects/, Sprints/
- Ready for submodule integration
- Generated by Workstation v1.0.0"
    
    cd "$SCRIPT_DIR"
    log_success "SSOT repository created: $ssot_path"
    echo ""
}

# Create KB-Core submodule
create_kb_core() {
    local kb_name="KB-Core"
    local kb_repo="kb-core"
    local kb_path="../${kb_repo}"
    local ssot_path="../SSOT-${ORG_NAME}"
    
    log_info "Creating KB-Core repository..."
    
    if [[ -d "$kb_path" ]]; then
        log_warn "KB-Core directory exists, skipping creation"
    else
        mkdir -p "$kb_path"
        cd "$kb_path"
        git init
        
        # Create KB-Core structure
        cat > README.md <<EOF
# KB-Core v1.0.0

**Core Semantic Foundation for Workstation Organizations**

## Purpose

Defines the formal semantics, entities, and structural rules used across all SSOTs.

## Entity Definitions

### Organization
- **Name**: Organization identifier
- **SSOT**: Root repository reference
- **Owner**: GitHub owner

### Seat
An isolated context for an AI agent:
- Dedicated memory space (.openclaw/workspace/)
- Specific tools/configuration
- Clear boundaries and permissions

### Project
A scoped body of work:
- Defined objectives
- Associated Seats
- Linked KBs

### Sprint
Time-boxed iteration:
- Start/end dates
- Associated Projects
- Deliverables

## Naming Conventions

- **Seats**: PascalCase (e.g., Developer, Researcher)
- **Projects**: kebab-case (e.g., api-redesign)
- **Sprints**: YYYY-MM-description (e.g., 2026-03-foundation)
- **KBs**: KB-PascalCase (e.g., KB-Core, KB-Engineering)

## Extension

Extend KB-Core by:
1. Creating domain-specific KBs as separate repos
2. Referencing (never redefining) Core entities
3. Adding organization-specific extensions in SSOT

## Versioning

- **MAJOR**: Semantic breaking change
- **MINOR**: Additive extension
- **PATCH**: Clarification, no semantic change
EOF

        # Create .gitignore
        cat > .gitignore <<'GITIGNORE'
# Environment
.env
.env.*
!.env.example

# OS
.DS_Store
Thumbs.db

# Editors
.vscode/
.idea/
*.swp
*.swo
GITIGNORE

        git add -A
        git commit -m "Initial KB-Core v1.0.0

Core semantic foundation for Workstation organizations
- Entity definitions
- Naming conventions
- Extension guidelines"
        
        cd "$SCRIPT_DIR"
        log_success "KB-Core repository created: $kb_path"
    fi
    
    # Add as submodule to SSOT
    log_info "Adding KB-Core as submodule to SSOT..."
    cd "$ssot_path"
    git submodule add "../../${kb_repo}" KBs/KB-Core 2>/dev/null || log_warn "KB-Core submodule already exists"
    git commit -m "Add KB-Core submodule" || log_info "Nothing to commit"
    cd "$SCRIPT_DIR"
}

# Main execution
main() {
    echo "=========================================="
    echo "  Workstation Installer"
    echo "  Agent-Ready Organizational Workspace"
    echo "=========================================="
    echo ""
    
    check_dependencies
    setup_environment
    create_ssot_repo
    create_kb_core
    
    echo "=========================================="
    log_success "Workstation initialized successfully!"
    echo "=========================================="
    echo ""
    echo "Created:"
    echo "  📁 ../SSOT-${ORG_NAME}/       # Your SSOT repository"
    echo "  📁 ../kb-core/                # KB-Core (semantic foundation)"
    echo ""
    echo "Next steps:"
    echo ""
    echo "  1. Navigate to your SSOT:"
    echo "     cd ../SSOT-${ORG_NAME}"
    echo ""
    echo "  2. Create your first Seat:"
    echo "     bash ../workstation/scripts/create-seat.sh Developer"
    echo ""
    echo "  3. Create a Project:"
    echo "     mkdir Projects/my-project"
    echo ""
    echo "  4. Push to GitHub:"
    echo "     cd ../SSOT-${ORG_NAME}"
    echo "     git remote add origin https://github.com/$GITHUB_OWNER/SSOT-${ORG_NAME}.git"
    echo "     git push -u origin main"
    echo ""
    echo "     cd ../kb-core"
    echo "     git remote add origin https://github.com/$GITHUB_OWNER/kb-core.git"
    echo "     git push -u origin main"
    echo ""
}

main "$@"
