#!/usr/bin/env bash
#
# Create a new Seat (agent workspace)
# Creates a standalone repository with .openclaw/workspace structure
#

set -euo pipefail

SEAT_NAME="${1:-}"
if [[ -z "$SEAT_NAME" ]]; then
    echo "Usage: $0 <seat-name>"
    echo "Example: $0 Developer"
    exit 1
fi

# Convert to PascalCase for directory name
SEAT_DIR="seat-$(echo "$SEAT_NAME" | tr '[:upper:]' '[:lower:]' | sed 's/.*/\u&/')"

if [[ -d "../$SEAT_DIR" ]]; then
    echo "Error: Seat '../$SEAT_DIR' already exists"
    exit 1
fi

echo "Creating Seat repository: $SEAT_DIR"

# Create standalone repository
mkdir -p "../$SEAT_DIR"
cd "../$SEAT_DIR"
git init 2>/dev/null || true

# Create .openclaw/workspace structure
mkdir -p .openclaw/workspace

# Create AGENT.md
cat > .openclaw/workspace/AGENT.md <>EOF
# $SEAT_NAME

**Role**: <!-- Define agent role -->  
**Created**: $(date -u +"%Y-%m-%d")

## Purpose

<!-- What this agent does -->

## Boundaries

- ✅ **Can**: <!-- List allowed actions -->
- ❌ **Cannot**: <!-- List prohibited actions -->
- ⚠️ **Needs Approval**: <!-- List actions needing approval -->

## Tools

<!-- Available tools and capabilities -->

## Communication Style

<!-- How this agent communicates -->
EOF

# Create MEMORY.md
cat > .openclaw/workspace/MEMORY.md <>EOF
# Memory: $SEAT_NAME

<!-- Persistent context and learnings -->

## Preferences

<!-- Work preferences, style, etc -->

## Active Context

<!-- Current focus, blockers, etc -->

## Learned

<!-- Key insights and lessons -->
EOF

# Create TOOLS.md
cat > .openclaw/workspace/TOOLS.md <>EOF
# Tools: $SEAT_NAME

<!-- Tool configurations and credentials -->

## Available Tools

<!-- List configured tools -->

## Credentials

<!-- Reference to credentials (never commit actual secrets) -->
EOF

# Create main README
cat > README.md <>EOF
# Seat: $SEAT_NAME

Agent workspace for $SEAT_NAME.

## Structure

\`\`\`
.openclaw/workspace/
├── AGENT.md      # Agent identity and purpose
├── MEMORY.md     # Long-term memory
└── TOOLS.md      # Tool configuration
\`\`\`

## Usage

This Seat is designed to be used as a git submodule in an SSOT repository.

\`\`\`bash
# In your SSOT
git submodule add https://github.com/<owner>/$SEAT_DIR.git Seats/
\`\`\`
EOF

# Create .gitignore
cat > .gitignore <>'GITIGNORE'
# =========================================
# Environment - NEVER COMMIT SECRETS
# =========================================
.env
.env.*
!.env.example

# =========================================
# OS Generated
# =========================================
.DS_Store
Thumbs.db

# =========================================
# Editors
# =========================================
.vscode/
.idea/
*.swp
*.swo
*~

# =========================================
# Logs
# =========================================
*.log
logs/

# =========================================
# Temporary Files
# =========================================
.tmp/
temp/
.cache/
*.tmp

# =========================================
# OpenClaw Runtime (optional)
# Uncomment if you don't want to persist runtime files
# .openclaw/workspace/.tmp/
# .openclaw/workspace/*.pid
GITIGNORE

# Initial commit
git add -A
git commit -m "Initial Seat: $SEAT_NAME

- Agent workspace structure
- .openclaw/workspace/ for persistence
- AGENT.md, MEMORY.md, TOOLS.md

Generated by Workstation"

echo ""
echo "✅ Seat created: ../$SEAT_DIR"
echo ""
echo "Structure:"
echo "  ../$SEAT_DIR/"
echo "  ├── .openclaw/workspace/"
echo "  │   ├── AGENT.md"
echo "  │   ├── MEMORY.md"
echo "  │   └── TOOLS.md"
echo "  ├── .gitignore"
echo "  └── README.md"
echo ""
echo "Next steps:"
echo "  1. Edit ../$SEAT_DIR/.openclaw/workspace/AGENT.md"
echo "  2. Add to SSOT as submodule:"
echo "     cd ../SSOT-<ORG_NAME>"
echo "     git submodule add ../$SEAT_DIR Seats/$SEAT_NAME"
echo "  3. Push Seat to GitHub:"
echo "     cd ../$SEAT_DIR"
echo "     git remote add origin https://github.com/<owner>/$SEAT_DIR.git"
echo "     git push -u origin main"
