#!/usr/bin/env bash
#
# Create a new Seat (agent workspace)
# Creates: Seat-$SeatName-$ORG_NAME as standalone repository
#

set -euo pipefail

SEAT_NAME="${1:-}"
if [[ -z "$SEAT_NAME" ]]; then
    echo "Usage: $0 <seat-name>"
    echo "Example: $0 Developer"
    exit 1
fi

# Get ORG_NAME from environment or error
if [[ -z "${ORG_NAME:-}" ]]; then
    if [[ -f ".env" ]]; then
        source .env
    fi
fi

if [[ -z "${ORG_NAME:-}" ]]; then
    echo "Error: ORG_NAME not set"
    echo "Set it in .env or environment variable"
    exit 1
fi

# Convert SeatName to PascalCase
SEAT_PASCAL=$(echo "$SEAT_NAME" | sed 's/.*/\u&/')
REPO_NAME="Seat-${SEAT_PASCAL}-${ORG_NAME}"
REPO_DIR="../${REPO_NAME}"

if [[ -d "$REPO_DIR" ]]; then
    echo "Error: Seat '$REPO_DIR' already exists"
    exit 1
fi

echo "Creating Seat repository: $REPO_NAME"

# Create standalone repository
mkdir -p "$REPO_DIR"
cd "$REPO_DIR"
git init 2>/dev/null || true

# Create .openclaw/workspace structure
mkdir -p .openclaw/workspace

# Create AGENT.md
AGENT_MD="# $SEAT_NAME

**Organization**: $ORG_NAME  
**Role**: DEFINE_AGENT_ROLE  
**Created**: $(date -u +"%Y-%m-%d")

## Purpose

What this agent does.

## Boundaries

- **Can**: List allowed actions
- **Cannot**: List prohibited actions
- **Needs Approval**: List actions needing approval

## Tools

Available tools and capabilities.

## Communication Style

How this agent communicates.
"
echo "$AGENT_MD" > .openclaw/workspace/AGENT.md

# Create MEMORY.md
MEMORY_MD="# Memory: $SEAT_NAME ($ORG_NAME)

Persistent context and learnings.

## Preferences

Work preferences, style, etc.

## Active Context

Current focus, blockers, etc.

## Learned

Key insights and lessons.
"
echo "$MEMORY_MD" > .openclaw/workspace/MEMORY.md

# Create TOOLS.md
TOOLS_MD="# Tools: $SEAT_NAME ($ORG_NAME)

Tool configurations and credentials.

## Available Tools

List configured tools.

## Credentials

Reference to credentials (never commit actual secrets).
"
echo "$TOOLS_MD" > .openclaw/workspace/TOOLS.md

# Create main README
README="# Seat: $SEAT_NAME

Organization: **$ORG_NAME**

Agent workspace for $SEAT_NAME.

## Structure

\`\`\`
.openclaw/workspace/
├── AGENT.md      # Agent identity and purpose
├── MEMORY.md     # Long-term memory
└── TOOLS.md      # Tool configuration
\`\`\`

## Usage

This Seat is designed to be used as a git submodule in an SSOT repository.

\`\`\`bash
# In your SSOT
git submodule add https://github.com/OWNER/$REPO_NAME.git Seats/
\`\`\`

## Repository

- **Name**: $REPO_NAME
- **Organization**: $ORG_NAME
- **Created**: $(date -u +"%Y-%m-%d")
"
echo "$README" > README.md

# Create .gitignore
cat > .gitignore <>'GITIGNORE'
# Environment - NEVER COMMIT SECRETS
.env
.env.*
!.env.example

# OS
.DS_Store
Thumbs.db

# Editors
.vscode/
.idea/
*.swp
*.swo
*~

# Logs
*.log
logs/

# Temp
.tmp/
temp/
.cache/
*.tmp
GITIGNORE

# Initial commit
git add -A
git commit -m "Initial Seat: $SEAT_NAME for $ORG_NAME

- Agent workspace structure
- .openclaw/workspace/ for persistence
- AGENT.md, MEMORY.md, TOOLS.md

Generated by Workstation"

echo ""
echo "✅ Seat created: $REPO_DIR"
echo ""
echo "Structure:"
echo "  $REPO_DIR/"
echo "  ├── .openclaw/workspace/"
echo "  │   ├── AGENT.md"
echo "  │   ├── MEMORY.md"
echo "  │   └── TOOLS.md"
echo "  ├── .gitignore"
echo "  └── README.md"
echo ""
echo "Next steps:"
echo "  1. Edit $REPO_DIR/.openclaw/workspace/AGENT.md"
echo "  2. Add to SSOT as submodule:"
echo "     cd ../SSOT-${ORG_NAME}"
echo "     git submodule add ../$REPO_NAME Seats/$SEAT_PASCAL"
echo "  3. Push to GitHub:"
echo "     cd ../$REPO_DIR"
echo "     git remote add origin https://github.com/OWNER/$REPO_NAME.git"
echo "     git push -u origin main"
