#!/usr/bin/env bash
#
# Create a new Project
# Creates: Project-$ProjectName-$ORG_NAME as standalone repository
#

set -euo pipefail

PROJECT_NAME="${1:-}"
if [[ -z "$PROJECT_NAME" ]]; then
    echo "Usage: $0 <project-name>"
    echo "Example: $0 api-redesign"
    exit 1
fi

# Get ORG_NAME from environment or error
if [[ -z "${ORG_NAME:-}" ]]; then
    if [[ -f ".env" ]]; then
        source .env
    fi
fi

if [[ -z "${ORG_NAME:-}" ]]; then
    echo "Error: ORG_NAME not set"
    echo "Set it in .env or environment variable"
    exit 1
fi

# Convert project name to repo name format
# api-redesign → Project-ApiRedesign-$ORG_NAME
PROJECT_PASCAL=$(echo "$PROJECT_NAME" | sed -E 's/(^|-)([a-z])/\u\2/g' | sed 's/-//g')
REPO_NAME="Project-${PROJECT_PASCAL}-${ORG_NAME}"
REPO_DIR="../${REPO_NAME}"

if [[ -d "$REPO_DIR" ]]; then
    echo "Error: Project '$REPO_DIR' already exists"
    exit 1
fi

echo "Creating Project repository: $REPO_NAME"

# Create standalone repository
mkdir -p "$REPO_DIR"
cd "$REPO_DIR"
git init 2>/dev/null || true

# Create README
README="# Project: $PROJECT_NAME

**Organization**: $ORG_NAME  
**Status**: Planning  
**Created**: $(date -u +"%Y-%m-%d")  
**Last Updated**: $(date -u +"%Y-%m-%d")

## Objective

What this project achieves.

## Scope

**In Scope**:
- Item 1
- Item 2

**Out of Scope**:
- Item 1
- Item 2

## Related

- **Seats**: Link relevant seats
- **KBs**: Link knowledge bases

## Deliverables

- [ ] Deliverable 1
- [ ] Deliverable 2
- [ ] Deliverable 3

## Decisions

### YYYY-MM-DD: Decision Title

**Context**: Background  
**Decision**: What was decided  
**Consequences**: Impact

## Notes

Additional notes.
"
echo "$README" > README.md

# Create .gitignore
cat > .gitignore <>'GITIGNORE'
# Environment
.env
.env.local
.env.*
!.env.example

# Temporary files
*.tmp
.tmp/
temp/
cache/

# OS
.DS_Store
Thumbs.db

# Editors
.vscode/
.idea/
*.swp
GITIGNORE

# Create docs directory
mkdir -p docs
echo "# Documentation: $PROJECT_NAME

Project-specific documentation.

## Structure

- docs/architecture.md
- docs/api-spec.md
- docs/deployment.md
" > docs/README.md

# Initial commit
git add -A
git commit -m "Initial Project: $PROJECT_NAME for $ORG_NAME

- Project scaffolding
- README with structure
- docs/ directory

Generated by Workstation"

echo ""
echo "✅ Project created: $REPO_DIR"
echo ""
echo "Structure:"
echo "  $REPO_DIR/"
echo "  ├── docs/"
echo "  │   └── README.md"
echo "  ├── .gitignore"
echo "  └── README.md"
echo ""
echo "Next steps:"
echo "  1. Edit $REPO_DIR/README.md"
echo "  2. Add to SSOT as submodule:"
echo "     cd ../SSOT-${ORG_NAME}"
echo "     git submodule add ../$REPO_NAME Projects/$PROJECT_PASCAL"
echo "  3. Push to GitHub:"
echo "     cd ../$REPO_DIR"
echo "     git remote add origin https://github.com/OWNER/$REPO_NAME.git"
echo "     git push -u origin main"
